### ISSUE TITLE
cut mesh

### ISSUE THREAD

**Issue by shalinsirwani** [mlivesu/cinolib#117]
possible to cut mesh with set of 3d points on it.
if possible , example ??

**Comment by mlivesu** [comment]
I am not sure I understand the question. 
What do you need to do precisely?

**Comment by shalinsirwani** [comment]
i have mesh
[m1 - Copy.off.txt](https://github.com/mlivesu/cinolib/files/5915970/m1.-.Copy.off.txt)
and set of 3d points
[tt.txt](https://github.com/mlivesu/cinolib/files/5915973/tt.txt)

**now i need to cut this mesh with these set of 3d points ( these points are on the arbitrary plane ) ??**

**And what if i want to cut this mesh with any curved line ( set of 3d points ) ??**

**Comment by mlivesu** [comment]
This is not a well posed problem, and depending on how one thinks about it, it can be solved with different tools. 

As a starter: points do not "cut" a mesh. They can be "inserted" in the mesh, but unless they lie exactly on the surface, insertion is ambiguous too... 

If points lie exactly on the surface, one could process each point separately, find the triangle that contains it, and split the triangle to incorporate it

If points do not lie on the surface, but they jointly sample a certain cutting membrane, one could first define an implicit surface that interpolates this membrane (e.g. using RBF), and then cut the mesh with the membrane, splitting triangles that are traversed by the zero level set of the radial basis function

These are just two simple ways that came on top of my mind, and for which cinolib has all the basic ingredients. Please note that this library does not aim to provide high level algorithms like the one you are perhaps looking for, but it's rather a set of low level atomic tools that you can combine to do what you want. This implies that you must know in advance what you want to do, and how to achieve it. 

I am closing the issue.
