### ISSUE TITLE
Option: perspective and orthographic

### ISSUE THREAD

**Issue by 461353349** [mlivesu/cinolib#13]
@mlivesu I think we should supply an option swifting between perspective and orthographic. Orthographic is mostly used in Engineer and CAD/CAE. What about you?

**Comment by mlivesu** [comment]
I agree, it might be useful for some users. Unfortunately at the moment I do not have free cycles to spend implementing new features. I added this request to my TODO list and will work on it ASAP.
Thank you!

**Comment by mlivesu** [comment]
@461353349, I changed my mind and added this feature to the canvas. It took me less than expected. When the focus is on the canvas, key P switches between perspective and orthographic view. Copy/paste of points of view is also updated and restores the correct projection mode.

**Comment by 461353349** [comment]
It is nice of you!
