### ISSUE TITLE
Undefined reference to `orient2d' / `orient3d'

### ISSUE THREAD

**Issue by DanielaCabiddu** [mlivesu/cinolib#135]
**Files predicates.h/cpp**

**Functions**

           double orient2d(const double * pa, const double * pb, const double * pc);
           double orient3d(const double * pa, const double * pb, const double * pc, const double * pd);

are implemented if and only if CINOLIB_USES_EXACT_PREDICATES are not defined. 

If CINOLIB_USES_EXACT_PREDICATES is defined, building errors occur : Undefined reference to `orient2d' / `orient3d'.

**Comment by mlivesu** [comment]
The implementation of exact predicates is external to cinolib. If you want to use them, you must define the symbol `CINOLIB_USES_EXACT_PREDICATES` at compilation time and include in your project the file `cinolib/external/predicates/shewchuk.c`
