### ISSUE TITLE
how to use the hex_transition_install function?

### ISSUE THREAD

**Issue by zeroseven-hash** [mlivesu/cinolib#137]
I want to achieve a simple subdivision schme on hexmesh. I think the ‘'hex_transition_install’' function may help me a lot.But i don't know which verts should be set to true in transition_verts. Is there any examples?

**Comment by mlivesu** [comment]
Hi,

`hex_transition_install` may not be what you need. Its purpose is to install dual topological schemes to perform adaptive grid to hexmesh convertion (see our forthcoming SIGGRAPH paper [here](http://pers.ge.imati.cnr.it/livesu/papers/PLCGS21/PLCGS21.pdf))

If you are looking for simple midpoint subdivision you can look at `subdivision_midpoint`. It works for any polyhedral mesh, hexmesh included
