### ISSUE TITLE
no member named 'update_hex_quality'

### ISSUE THREAD

**Issue by MarsVegetables** [mlivesu/cinolib#151]
Hi,
When I try to compile LoopyCuts, I got a error from cinolib, the error is shown blow.
`In file included from ./definitions.h:30:
In file included from ../lib/cinolib/include/cinolib/meshes/meshes.h:49:
In file included from ../lib/cinolib/include/cinolib/meshes/hexmesh.h:124:
../lib/cinolib/include/cinolib/meshes/hexmesh.cpp:405:19: error: no member named 'update_hex_quality' in 'cinolib::Hexmesh<cinolib::Mesh_std_attributes, MV, ME, MF, MP>'
            this->update_hex_quality(pid);
            ~~~~  ^
export_helper.cpp:37:12: note: in instantiation of member function 'cinolib::Hexmesh<cinolib::Mesh_std_attributes, MV, ME, MF, MP>::poly_fix_orientation' requested here
        hm.poly_fix_orientation(); // meta mesh does not have globally consistent winding numbers...
           ^
In file included from export_helper.cpp:27:
In file included from ./export_helper.h:30:
In file included from ./state.h:36:
In file included from ./definitions.h:30:
In file included from ../lib/cinolib/include/cinolib/meshes/meshes.h:49:
In file included from ../lib/cinolib/include/cinolib/meshes/hexmesh.h:124:
../lib/cinolib/include/cinolib/meshes/hexmesh.cpp:415:19: error: no member named 'update_hex_quality' in 'cinolib::Hexmesh<cinolib::Mesh_std_attributes, MV, ME, MF, MP>'
            this->update_hex_quality();
            ~~~~  ^
21 warnings and 2 errors generated.
make: *** [export_helper.o] Error 1`

I tried to search the function in [3D5378](https://github.com/mlivesu/cinolib/tree/3d53718818480c99306d3d6830f49c3604d33ebd), But I can not find this function.
Any suggestion?
Thank you.

**Comment by mlivesu** [comment]
hi, there has been an update of the quality system in cinolib, the function is now called `update_quality`

**Comment by MarsVegetables** [comment]
> hi, there has been an update of the quality system in cinolib, the function is now called `update_quality`

Thank you for the quick reply,
but update_quality in the commit ([3D5378](https://github.com/mlivesu/cinolib/tree/3d53718818480c99306d3d6830f49c3604d33ebd)) which is used in LoopyCuts does not accept pid as argument.
`../lib/cinolib/include/cinolib/meshes/hexmesh.cpp:405:34: error: too many arguments to function call, expected 0, have 1
            this->update_quality(pid);
            ~~~~~~~~~~~~~~~~~~~~ ^~~
export_helper.cpp:37:12: note: in instantiation of member function 'cinolib::Hexmesh<cinolib::Mesh_std_attributes, MV, ME, MF, MP>::poly_fix_orientation' requested here
        hm.poly_fix_orientation(); // meta mesh does not have globally consistent winding numbers...
           ^
../lib/cinolib/include/cinolib/meshes/abstract_polyhedralmesh.h:111:22: note: 'update_quality' declared here
                void update_quality();
                     ^
21 warnings and 1 error generated.`
Should I just simply update cionolib to the newest version and then compile LoopyCuts?
Thank you.

**Comment by mlivesu** [comment]
sorry, the right call is `update_p_quality(pid)`

LoopyCuts does not compile with the latest CinoLib. There have been huge changes, especially in the GUI part, which used to be based on Qt, and now it is based on GLFW + ImGui
