### ISSUE TITLE
How to use remesh_Botsch_Kobbelt_2004 without gl

### ISSUE THREAD

**Issue by Another-Anonymous-User** [mlivesu/cinolib#154]
Hi, I would like to use remesh_Botsch_Kobbelt_2004 to remesh a surface using the api. The issue I am having is that remesh_Botsch_Kobbelt_2004 seems to require a DrawableTrimesh which in turn is dependent on gl  (my understanding is that gl is required for the GUI stuff, which I am not interested in). Is there a way of using remesh_Botsch_Kobbelt_2004 without needing gl?

**Comment by mlivesu** [comment]
correct, I have updated the file so that now you can pass just a simple Trimesh without the GL burden
As a side note: my implementation of the algorithm is non fully robust. There may be issues triggered by numerical precision

**Comment by Another-Anonymous-User** [comment]
Thanks! As an additional question, as far as I can see its not possible but maybe there is some trick to still accomplish it, is it in some way possible to pass a location dependent target_edge_length to `remesh_Botsch_Kobbelt_2004()`?

**Comment by mlivesu** [comment]
surely doable, but not supported in cinolib. I do not recall the details in the original paper, but it may be possible that the authors already explained how to implement this
