### ISSUE TITLE
Orient a closed surface mesh

### ISSUE THREAD

**Issue by Another-Anonymous-User** [mlivesu/cinolib#155]
Hi, Is there a build in way to save surface as an .stl file with its normals oriented outwards?

**Comment by mlivesu** [comment]
hi, there is a function called `write_STL` that does exactly this. You can find it in `cinolib/io/write_STL.h`

**Comment by Another-Anonymous-User** [comment]
But currently I am using `trimesh.save()` to create the stl which as far as I can tell from the source code uses the `write_STL` function you mention. However, the normals seem to have been randomly oriented and not consistently outwards.

**Comment by mlivesu** [comment]
A tiny clarification: if you load a method with inconsistent normals and then you save it as an STL... you'll just propagate the same inconsistent normals in the new file! There's no magic in the save method.

Perhaps what you need is an algorithm to re-orient a badly oriented discrete surface? I do not have it in cinolib, but it should be fairly easy for you to code one. You just have to start from a trusted triangle (e.g. the first triangle you intersect from a ray coming from the outside), fix that normal, and then propagate the same orientation to the adjacent elements via flooding. If the surface is orientable, the algorithm converges to a consistent mesh orientation. If it is not, you will try to assign an opposite normal to a triangle you already visited, and by then you would know that your surface is non-orientable (e.g. a Mobius strip)

**Comment by Another-Anonymous-User** [comment]
Thanks for the clarification, I was asking mostly hoping it would not be necessary to implement it or use some other library for it, but alas, there is no other option.
