### ISSUE TITLE
Is there a way to perform boolean operations (with texture map preservation)?

### ISSUE THREAD

**Issue by OlegJakushkin** [mlivesu/cinolib#16]
Havig two two sided textured OBJs, how one would be capable to merge and substract one from another combining textures in a new surface object? #

**Comment by mlivesu** [comment]
Hi, boolean operations between 3D shapes are not supported in the current version of cinolib. While I do not exclude that such a feature will be added in future versions of the library, at the moment I am not working on it. If you need robust 3D booleans I suggest you to take a look at libIGL, it might contain what you need.
