### ISSUE TITLE
error when run sliced_CLI_loader

### ISSUE THREAD

**Issue by Haidiye01** [mlivesu/cinolib#162]
![image](https://github.com/mlivesu/cinolib/assets/40328051/d36ccf81-588c-4775-b495-37f304c5c0d6)
my boost version is 1.80,and it popup error when run sliced_CLI_loader,how to solve it,thanks

**Comment by mlivesu** [comment]
Hi, I haven't had time to investigate it. The wrap to Boost (and all the few functions that currently depend on it) are temporarily disabled
