### ISSUE TITLE
Support for Semantic Versioning

### ISSUE THREAD

**Issue by lyrahgames** [mlivesu/cinolib#178]
Hello,

thank you very much for your tremendous work on this library!
Would it be possible to add support for semantic versioning?
I know that there is the `1.0` tag. However, it seems to be out of date.

**Comment by lyrahgames** [comment]
Thank you very much for the quick response and your detailed explanation.
Yes, please keep me up to date. FYI, I am currently involved in packaging CinoLib as [build2](https://build2.org/) package. As of that, semantic versioning would be very helpful.

**Comment by mlivesu** [comment]
Interesting. I'd like to take a look at the packaging once you are done.
I'll keep you posted as promised
