### ISSUE TITLE
intersection when rendering a .mesh file

### ISSUE THREAD

**Issue by yanyiss** [mlivesu/cinolib#179]
it seems many intersections when I slicing a .mesh file using 05_hexmesh_viewer
![image](https://github.com/mlivesu/cinolib/assets/61866455/5096d2eb-48f3-4570-85bc-4e4499b0a637)
[bunny_projected.zip](https://github.com/mlivesu/cinolib/files/14973356/bunny_projected.zip)

**Comment by mlivesu** [comment]
Hi, I am not sure what is the question here.
All the slicer does is to hide elements that have their centroid past a certain threshold, showing the others. What is being shown depends on the mesh. If the mesh contains intersecting elements, these elements will become visible. 
I guess this is a positive thing, usually one wants to slice to visually inspect the interior, right? :)

**Comment by yanyiss** [comment]
> Hi, I am not sure what is the question here. All the slicer does is to hide elements that have their centroid past a certain threshold, showing the others. What is being shown depends on the mesh. If the mesh contains intersecting elements, these elements will become visible. I guess this is a positive thing, usually one wants to slice to visually inspect the interior, right? :)

yeah, you are right. I do not check the mesh. I just generate the mesh from the code of your adaptive grid paper https://github.com/cg3hci/Gen-Adapt-Ref-for-Hexmeshing
by running
make_grid.exe --surface --input_mesh_path=bunny.obj --output_grid_path=bunny.mesh --strong_balancing --use_octree --max_refinement=10 --sanity_check=true --install_schemes=true --project_mesh=true
I thought there is no intersection to generate hex from a simple .obj by using that code.

**Comment by yanyiss** [comment]
but still strange... you can compare the following the pictures, the only difference is slicing: X. One is 0.575, the other is 0.554
![image](https://github.com/mlivesu/cinolib/assets/61866455/63b385b9-6974-463a-997d-492172223226)
![image](https://github.com/mlivesu/cinolib/assets/61866455/6b85912b-4c97-413b-9ad1-f0d46c53fe9d)
From the second picture, there is no intersection on the surface mesh. But there is intersection in the first picture.

**Comment by mlivesu** [comment]
the code you mentioned is guaranteed to produce an adaptively refined grid and a conforming hexahedral mesh out of it, but the projection part is completely heuristic (and really bad, to be honest) so projecting can create any sort of trouble. We never got time/people to work on the projection part. If you omit the `--project_mesh=true` in your call you'll get a provably valid mesh (but axis aligned)

For the last comment. Prior to slicing, only the external quads of the mesh are rendered. When you slice, also interior vertices attached to the current inner boundary between sliced and non sliced elements are shown, so it may happen that all of a sudden weird stuff appears during slicing

**Comment by yanyiss** [comment]
> the code you mentioned is guaranteed to produce an adaptively refined grid and a conforming hexahedral mesh out of it, but the projection part is completely heuristic (and really bad, to be honest) so projecting can create any sort of trouble. We never got time/people to work on the projection part. If you omit the `--project_mesh=true` in your call you'll get a provably valid mesh (but axis aligned)
> 
> For the last comment. Prior to slicing, only the external quads of the mesh are rendered. When you slice, also interior vertices attached to the current inner boundary between sliced and non sliced elements are shown, so it may happen that all of a sudden weird stuff appears during slicing

I got it. Thanks for your reply.
