### ISSUE TITLE
how to plot vectors on the mesh

### ISSUE THREAD

**Issue by lzrocking** [mlivesu/cinolib#182]
hi, I have test the "heat_geodesics" example. It is awesome!
I want plot the vector field on the mesh.
In the function “compute_geodesics”, it tells us the final result of the geodesics, which was copied to the mesh by the function of “copy_to_mesh”. Then the mesh object, which is inherited from the DrawableObject class, is plotted by the GLcanvas object.
Motivated by this mechanism, I’ve noticed that there is a module called “drawable_vector_field”, which is defined by the “drawable_vector_field.h” and “drawable_vector_field.cpp”. And the drawable_vector_field class also is inherited from the DrawableObject class. Does that mean the drawable_vector_field object could be pushed into the GLcanvas and show the drawable_vector_field.
Furthermore, in the function “compute_geodesics”, “VectorField grad = G * heat”. The “grad” object is a “VectorField”, which actually is a Eigen::VectorXd. And the drawable_vector_field has a constructor called DrawableVectorField(const Eigen::MatrixBase<OtherDerived>& other) : Eigen::VectorXd(other) .So, is it possible to plot the VectorField grad by the drawable_vector_field on the mesh?
Thank you very much!

**Comment by mlivesu** [comment]
hi, absolutely!
You can do it directly from the heat_geodesics example. If you press the `TAB` key, a side menu bar will show up. All you have to do it to expand the menu `Vector Fields` and thick the checkbox to show it. You can play with arrow size and colors to adjust the view. Here is a visual example

<img width="1512" alt="a" src="https://github.com/mlivesu/cinolib/assets/7881910/c8156793-b886-45f9-bdec-5a437eda01da">
<img width="1512" alt="b" src="https://github.com/mlivesu/cinolib/assets/7881910/d5fd9621-1ae2-4d21-9488-19aa161c04ea">

**Comment by lzrocking** [comment]
It dose work! Thank you very much!
